model_paras:
  motion_channels: 2
  num_flows: 1
  num_slots: 2000
  shrink_thres: 0.0005
  feature_root: 32
  skip_conn: True
  mem_usage: [ False, True, True, True ]
  skip_ops: [ "none", "concat", "concat" ]

# exp settings
dataset_base_dir: ./carla_data
dataset_name: carla_local
exp_name: carla_local_ML_MemAE_SC_final_day
ckpt_root: /disk/vanishing_data/hb344/ML_memeAE/ckpt
log_root: /disk/vanishing_data/hb344/ML_memeAE/log
eval_root: /disk/vanishing_data/hb344/ML_memeAE/eval
device: cuda:0

pretrained: False
model_savename: ML_nmeme_model.pth
# num of iterations to log
logevery: 100

# num of epoch to save models
saveevery: 5

# training setting
num_epochs: 150
batchsize: 256
lr: 0.0001
num_workers: 8
lam_sparse: 0.0002
lam_recon: 1.0



